### ISSUE TITLE
Add hostname annotations

### ISSUE THREAD

**Issue by bbockelm** [CoffeaTeam/jhub#17]
I was able to get `external-dns` working and setup an integration with CloudFlare.  Now, we can add hostnames to services like so:

```
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: brian-2ebockelman-40cern-2ech.dask.coffea.casa
    external-dns.alpha.kubernetes.io/ttl: "120"
```

Let's edit the JupyterHub configuration and set these annotations around here:

https://github.com/CoffeaTeam/jhub/blob/master/files/hub/jupyterhub_config.py#L289

Then, instead of the `HOST_IP` here:

https://github.com/CoffeaTeam/jhub/blob/master/files/hub/jupyterhub_config.py#L321

We can instead set a proper DNS name.
